// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Jacobbrewer1/puppet-summary/pkg/logging"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func initializeApp() (*app, error) {
	name := _wireNameValue
	config := logging.NewConfig(name)
	logger, err := logging.CommonLogger(config)
	if err != nil {
		return nil, err
	}
	router := mux.NewRouter()
	mainApp := newApp(logger, router)
	return mainApp, nil
}

var (
	_wireNameValue = logging.Name(appName)
)
