openapi: 3.0.0
info:
  version: latest
  title: Puppet Summary API
  description: Documentation for Puppet Summary API

paths:
  /upload:
    post:
      summary: Upload a puppet report
      operationId: UploadPuppetReport
      description: Upload a puppet report
      security:
        - bearerAuth: []
      requestBody:
        description: Binary puppet report
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: Puppet report uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadPuppetReportResponse'
        '400':
          description: Bad request
        '409':
          description: Report already exists
        '500':
          description: Error returned from upstream request
  /nodes:
    get:
      summary: Get all nodes
      operationId: GetAllNodes
      description: Get all nodes
      responses:
        '200':
          description: Get all nodes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllNodesResponse'
        '400':
          description: Bad request
        '500':
          description: Error returned from upstream request
  /nodes/enviroment/{env}:
    get:
      summary: Get all nodes by environment
      operationId: GetAllNodesByEnvironment
      description: Get all nodes by environment
      parameters:
        - name: env
          in: path
          description: The environment to get nodes from
          required: true
          schema:
            $ref: '#/components/schemas/environment'
      responses:
        '200':
          description: Get all nodes by environment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllNodesResponse'
        '400':
          description: Bad request
        '500':
          description: Error returned from upstream request

components:
  schemas:
    environment:
      description: The environment that a machine is reporting from.
      type: string
      enum:
        - PRODUCTION
        - STAGING
        - DEVELOPMENT
      example: PRODUCTION

    state:
      description: The estate of the machine from the report.
      type: string
      enum:
        - CHANGED
        - UNCHANGED
        - FAILED
        - SKIPPED
      example: CHANGED

    uploadPuppetReportResponse:
      type: object
      properties:
        id:
          type: string
        fqdn:
          type: string
        puppet_version:
          type: number
        env:
          type: string
        state:
          type: string
        exec_time:
          type: string
          format: date-time
        runtime:
          type: string
        failed:
          type: integer
        changed:
          type: integer
        skipped:
          type: integer
        total:
          type: integer
        log_messages:
          type: array
          items:
            type: string
        resources_failed:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
        resources_changed:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
        resources_skipped:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
        resources_ok:
          type: array
          items:
            $ref: '#/components/schemas/Resource'

    Resource:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        file:
          type: string
        line:
          type: string

    getAllNodesResponse:
      type: array
      items:
        type: object
        properties:
          nodes:
            type: array
            items:
              $ref: '#/components/schemas/node'

    node:
      properties:
        fqdn:
          description: The Hostname of the machine.
          type: string
          example: 'fqdn.domain.com'
        env:
          $ref: '#/components/schemas/environment'
        state:
          $ref: '#/components/schemas/state'
        exec_time:
          description: The time of when the Puppet Report Ran. (time.RFC3339 format)
          type: string
          example: '2024-02-13T10:00:09Z'
        runtime:
          description: How long the puppet apply took.
          type: string
          example: 23s
