// Package summary provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package summary

import (
	"context"
	"fmt"
	"net/http"
	"strings"

	"github.com/Jacobbrewer1/puppet-summary/pkg/request"
	"github.com/gorilla/mux"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

const appName = "summary"

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all nodes
	// (GET /nodes)
	GetAllNodes(w http.ResponseWriter, r *http.Request)
	// Upload a puppet report
	// (POST /upload)
	UploadPuppetReport(w http.ResponseWriter, r *http.Request)
}

type AuthOption int

const (
	// AuthOptionNone is the option for no authentication.
	AuthOptionNone AuthOption = iota

	// AuthOptionInternal is the option to only allow internal traffic.
	AuthOptionInternal

	// AuthOptionRequired is the option for required authentication.
	AuthOptionRequired
)

var (
	// httpTotalRequests is the total number of http requests.
	httpTotalRequests = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name:      "http_requests_total",
			Namespace: appName,
			Help:      "Total number of http requests",
		},
		[]string{"path", "method", "status_code"},
	)

	// httpRequestDuration is the duration of the http request.
	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:      "http_request_duration_seconds",
			Namespace: appName,
			Help:      "Duration of the http request",
		},
		[]string{"path", "method", "status_code"},
	)

	// httpRequestSize is the size of the http request.
	httpRequestSize = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:      "http_request_size",
			Namespace: appName,
			Help:      "Size of the http request",
		},
		[]string{"path", "method", "status_code"},
	)
)

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler, AuthOption) http.Handler

// GetAllNodes operation middleware
func (siw *ServerInterfaceWrapper) GetAllNodes(w http.ResponseWriter, r *http.Request) {
	w = request.NewClientWriter(w)

	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllNodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		// Check to see what kind of authentication is required

		opt := AuthOptionNone

		handler = middleware(handler, opt)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

const BearerAuthToken = "BearerAuthToken"

// UploadPuppetReport operation middleware
func (siw *ServerInterfaceWrapper) UploadPuppetReport(w http.ResponseWriter, r *http.Request) {
	w = request.NewClientWriter(w)

	ctx := r.Context()

	token := r.Header.Get("Authorization")
	if token == "" {
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization"})
		return
	}
	token = strings.TrimPrefix(token, "Bearer ")
	ctx = context.WithValue(ctx, BearerAuthToken, token)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPuppetReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		// Check to see what kind of authentication is required

		opt := AuthOptionRequired

		handler = middleware(handler, opt)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/nodes", wrapper.GetAllNodes).Methods("GET")

	r.HandleFunc(options.BaseURL+"/upload", wrapper.UploadPuppetReport).Methods("POST")

	return r
}
