name: Production Deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

# We only want one build to run at a time for each branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build All
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
          cache-dependency-path: "**/*.sum"

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker images
      - name: Make all
        run: |
          export CGO_ENABLED=0
          make CI-all

  deploy-puppet-summary:
    # Only run if release triggered the workflow
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    name: Deploy Puppet Summary
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit sha
        id: vars_deploy
        run: |
          echo "sha_short_deploy=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: "Configure git for private repositories"
        run: git config --global url."https://x:${{ secrets.PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      # Checkout the common chart
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          repository: Jacobbrewer1/supporting-charts
          path: ./charts
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy matchmaker
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade --install puppet-summary ./charts/charts/puppet-summary --set image.tag=${{ steps.vars_deploy.outputs.sha_short_deploy }}
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'
