name: Production Deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

jobs:
#  build:
#    name: Build All
#    permissions: write-all
#    uses: jacobbrewer1/puppet-summary/.github/workflows/ci-docker.yml@main
#    secrets: inherit

  deploy:
    name: Deploy Puppet Summary
    runs-on: ubuntu-latest
#    needs: [ build ]
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit
        id: get_commit
        run: echo "sha_short_deploy=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Get GitHubAPI token
        id: get_token
        uses: Jacobbrewer1/secret-shipper@v0.1.4
        with:
          vault-address: ${{ secrets.VAULT_HOST }}
          vault-user: ${{ secrets.VAULT_USER }}
          vault-password: ${{ secrets.VAULT_PASSWORD }}
          action: get
          mount: ${{ secrets.VAULT_KVV2_MOUNT }}
          name: ${{ secrets.VAULT_GITHUB_API_NAME }}
          key: ${{ secrets.VAULT_GITHUB_API_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          repository: Jacobbrewer1/supporting-charts
          path: ./charts
          token: ${{ steps.get_token.outputs.retrieved-secret }}

      - name: Deploy Puppet Summary
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm upgrade --install puppet-summary ./charts --values charts/valueFiles/prod-1/puppet-summary.yaml --set image.tag=${{ steps.get_commit.outputs.sha_short_deploy }}
          kubeconfig: '${{ secrets.KUBE_CONFIG }}'