name: Production Deploy

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

# We only want one build to run at a time for each branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build All
    permissions: write-all
    uses: jacobbrewer1/puppet-summary/.github/workflows/ci-docker.yml@main
    secrets: inherit

  setup:
    name: Setup
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit
        id: get_commit
        run: echo "sha_short_deploy=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy Puppet Summary
    runs-on: ubuntu-latest
    needs: [build, setup]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          repository: Jacobbrewer1/supporting-charts
          path: ./charts
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy Puppet Summary
        uses: ./.github/workflows/ci-deploy-puppet-summary.yml